[workspace]
resolver = "2"
members = ["gen", "hand"]

[profile.release]
codegen-units = 1
debug-assertions = false
incremental = false
lto = true
opt-level = "s"
# overflow-checks = false
panic = 'abort'
rpath = false
strip = true
